- name: service-restart-jenkins
  service:
    name: jenkins
    state: restarted
  listen:
    - restart-jenkins

- name: service-jenkins-wait-8090-login
  uri:
    url: "http://{{ ansible_host }}:8080/crumbIssuer/api/json"
    force_basic_auth: true
    url_username: "{{ jenkins_admin_user }}"
    url_password: "{{ jenkins_admin_pass }}"
    status_code:  [200, 301, 302, 401, 403, 503]
    force: yes
    validate_certs: yes
    use_proxy: no
  register: sjw_result
  check_mode: no
  until: sjw_result.status in [200]
  retries: 20
  delay: 6
  listen:
    - restart-jenkins
